name: RPG
main: nl.naxanria.rpg.Plugin
version: 1.0.@BUILD@
authors: [Naxanria]
depend: []
description:
commands:
  spawn:
    description: Teleports the user to spawn.
  rpg:
    description: Teleports the user to the rpg world.
  setspawn:
    decription: Sets the spawn at the user location.
  spawncreature:
    description: Spawns a creature;
  party:
    description: Party commands
  partychat:
    description: Chat in party.
    aliases: [pc]
  setitemdamage:
    description: set the item damage
  rpgdebug:
    description: starts debug
  setmaxhealth:
    description: Sets the maxhealth of a player.
  spawner:
    description: spawner commands.
